-- Seed data for local development
-- Reproducible local demo dataset for slices 01-05:
--   pnpm local:reset:demo
--   pnpm local:seed:demo
--
-- Local DB smoke data for slices 01-05 is seeded with:
--   pnpm qa:seed:01-05 -- --user-id <supabase-user-uuid>
--
-- The repo now carries the baseline schema required for slices 01-05, but the
-- richer smoke dataset still lives in the service-role seeder script so a
-- tester can target a specific authenticated user account on demand.
