import { expect, test } from "@playwright/test";
import { installAccountLibraryVisualRoutes, setE2EAuthOverride } from "./helpers/mock-routes";
import { installEmptyYoutubeNotificationRoutes } from "./helpers/youtube-background-extraction";

const date = "2026-09-28";
const columnId = "20000000-0000-4000-8000-000000000001";
const nutrition = { calculation_status: "complete", calories_kcal: 258.4, carbohydrate_g: 39.6, protein_g: 6.4, fat_g: 7.4, sodium_mg: 123.4 };
const entry = { id: "10000000-0000-4000-8000-000000000001", revision: 1, consumed_at: null, consumed_local_date: date, timezone_name_snapshot: "Asia/Seoul", meal_plan_column_id: columnId, slot_name_snapshot: "아침", source: { type: "ingredient", id: "30000000-0000-4000-8000-000000000001" }, quantity: { amount: 125.5, unit: "g" }, display_name: "딸기 우유 푸딩", display_brand: null, nutrition, created_at: `${date}T00:00:00Z`, updated_at: `${date}T00:00:00Z` };
const success = (data: unknown) => ({ success: true, data, error: null });
for (const width of [375, 1280]) test(`meal log redesign graphs and edit sheet ${width}px`, async ({ page }, testInfo) => {
  const origin = new URL(process.env.PLAYWRIGHT_BASE_URL ?? "http://127.0.0.1:3200");
  if (!["127.0.0.1", "localhost"].includes(origin.hostname)) throw new Error("Local QA only");
  await page.setViewportSize({ width, height: 812 });
  await setE2EAuthOverride(page);
  await installAccountLibraryVisualRoutes(page);
  await installEmptyYoutubeNotificationRoutes(page);
  await page.route("**/api/v1/meal-log/recent?*", route => route.fulfill({ json: success({ items: [], next_cursor: null, has_next: false }) }));
  await page.route("**/api/v1/cooked-batches?*", route => route.fulfill({ json: success({ items: [{ id: "40000000-0000-4000-8000-000000000001", recipe_id: "30000000-0000-4000-8000-000000000001", recipe_title: "김치찌개", recipe_thumbnail_url: null, status: "leftover", cooked_at: `${date}T00:00:00Z`, cooking_servings: 2, finished_weight_g: 800, remaining_weight_g: 600, weight_status: "known", weight_source: "estimated", batch_status: "available", depleted_reason: null, revision: 1, nutrition_calculation_status: "complete", current_unweighed_closure_event_id: null }], next_cursor: null, has_next: false }) }));
  await page.route("**/api/v1/meal-log/nutrition-preview?*", route => {
    const params = new URL(route.request().url()).searchParams;
    return route.fulfill({ json: success({ source: { type: params.get("source_type"), id: params.get("source_id") }, quantity: { amount: Number(params.get("amount")), unit: params.get("unit") }, nutrition }) });
  });
  await page.route("**/api/v1/meal-log?*", route => {
    const day = new URL(route.request().url()).searchParams.get("date")!;
    const entries = day === date ? [entry] : [];
    return route.fulfill({ json: success({ date: day, active_columns: [{ id: columnId, name: "아침", sort_order: 0 }, { id: "20000000-0000-4000-8000-000000000002", name: "점심", sort_order: 1 }], active_sections: [{ meal_plan_column_id: columnId, slot_name_snapshot: "아침", sort_order: 0, entries, subtotal: nutrition, incomplete_count: 0 }], deleted_column_sections: [], entries, day_total: { ...nutrition, incomplete_count: 0 } }) });
  });
  await page.goto(`/planner?segment=log&date=${date}`);
  const card = page.locator(`[data-planner-date="${date}"]`);
  await expect(card.getByRole("button", { name: /식사 기록 상세/ })).toBeVisible();
  await expect(page.locator("[data-planner-date]")).toHaveCount(1);
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
  const bar = card.getByRole("img");
  await expect(bar).toHaveCSS("height", "4px");
  const summary = card.getByRole("region", { name: "하루 영양" });
  await expect(summary.getByText("9월 28일", { exact: true })).toBeVisible();
  await expect(summary.locator("dt")).toHaveText(["탄", "단", "지"]);
  await expect(summary).toContainText("258 kcal");
  await expect(summary).not.toContainText("258.4");
  await expect(summary.getByText("하루 영양", { exact: true })).toHaveCount(0);
  await page.screenshot({ path: testInfo.outputPath("log-list.png") });
  await card.getByRole("button", { name: "하루 영양 상세 보기" }).click();
  const nutritionDetail = page.getByRole("dialog", { name: "하루 영양 상세" });
  await expect(nutritionDetail.getByRole("img", { name: "끼니별 열량 그래프" })).toBeVisible();
  await expect(nutritionDetail.getByRole("heading", { name: "9월 28일", exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("day-calories.png") });
  await nutritionDetail.getByRole("button", { name: "단백질", exact: true }).click();
  await expect(nutritionDetail.getByRole("img", { name: "끼니별 단백질 그래프" })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("day-protein.png") });
  await nutritionDetail.getByRole("button", { name: /딸기 우유 푸딩/ }).click();
  const detail = page.getByRole("dialog", { name: "식사 기록 상세" });
  await expect(detail.getByRole("textbox")).toHaveCount(0);
  await expect(detail.getByRole("button", { name: "아침에 먹은 음식 추가" })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("record-detail.png") });
  // The retained detail must remain behind the add sheet, including this nested day-detail path.
  await detail.getByRole("button", { name: "아침에 먹은 음식 추가" }).click();
  const add = page.getByRole("dialog", { name: "먹은 음식 추가" });
  // Inert backgrounds let pointer hit-testing pass through even when their pixels cover the sheet.
  const retainedDetailLayer = await page.locator('[aria-label="식사 기록 상세"]').evaluate(node => Number(getComputedStyle(node).zIndex));
  const addLayer = await add.evaluate(node => Number(getComputedStyle(node.parentElement!).zIndex));
  expect(addLayer).toBeGreaterThan(retainedDetailLayer);
  await add.getByRole("tab", { name: "요리한 음식", exact: true }).click();
  await add.getByRole("button", { name: /김치찌개/ }).click();
  await expect(add.getByRole("textbox", { name: "먹은 양" })).toHaveValue("100");
  await expect(add.getByRole("heading", { name: "9월 28일 아침" })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("record-detail-add.png") });
  await add.getByRole("button", { name: "닫기", exact: true }).click();
  await expect(add).toHaveCount(0);
  await expect(detail.getByRole("heading", { name: "9월 28일 아침" })).toBeVisible();
  await detail.getByRole("button", { name: "식사 기록 수정" }).click();
  const edit = page.getByRole("dialog", { name: "9월 28일 아침" });
  await edit.getByRole("textbox", { name: "먹은 양" }).fill("80.5");
  await expect(edit).toContainText("81g 기준");
  const amount = edit.getByRole("textbox", { name: "먹은 양" });
  await expect(amount).toBeFocused();
  await expect(amount).toHaveCSS("box-shadow", "none");
  await expect(amount).toHaveCSS("outline-style", "none");
  await expect(amount).toHaveCSS("border-top-width", "0px");
  await expect(amount).toHaveCSS("font-size", "16px");
  await expect(amount.locator("..")).not.toHaveCSS("box-shadow", "none");
  await page.screenshot({ path: testInfo.outputPath("record-edit.png") });
  await edit.getByRole("button", { name: "취소", exact: true }).click();
  await expect(edit).toContainText("변경사항을 버릴까요?");
  await edit.getByRole("button", { name: "변경사항 버리기" }).click();
  await expect(detail).toBeVisible();
  await detail.getByRole("button", { name: "기록 삭제" }).click();
  const remove = page.getByRole("dialog", { name: "9월 28일 아침" });
  await expect(remove).not.toContainText("돌려놓아요");
  await page.screenshot({ path: testInfo.outputPath("record-delete.png") });
  await remove.getByRole("button", { name: "취소", exact: true }).click();
  await detail.getByRole("button", { name: "식사 기록으로 돌아가기" }).click();
  await expect(nutritionDetail.getByRole("button", { name: "단백질", exact: true })).toHaveAttribute("aria-pressed", "true");
});
