import { execFileSync } from 'node:child_process';
import { randomBytes, createHash } from 'node:crypto';
import { mkdtemp, writeFile, chmod, rm, realpath } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { assertRound2Collection, assertRound2Origin, assertRound2Secrets, checkRound2LeadReadiness, readRound2RuntimeConfig, resolveRound2TrustedIp, isRound2LocalPreview } from '@/lib/server/marketing-round2-runtime';
const names = ['PAGE', 'COOKIE', 'BOOTSTRAP', 'EVENT', 'EMAIL', 'RECEIPT', 'RATE'];
const now = Date.parse('2026-09-12T00:00:00Z');
const release = execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
const control = { version: 1 as const, collection_enabled: true, lead_enabled: true, consent_generation: 1 };
const dirs: string[] = [];
function env() { return Object.fromEntries([...names.map(name => [`MUMEOK_ROUND2_${name}_SECRET`, randomBytes(32).toString('base64url')]), ['MUMEOK_ROUND2_ENABLED', 'true'], ['MUMEOK_ROUND2_LEADS_ENABLED', 'true'], ['MUMEOK_ROUND2_RELEASE_SHA', release], ['MUMEOK_ROUND2_TURNSTILE_SECRET_KEY', randomBytes(32).toString('base64url')]]); }
function request(origin = 'https://app.mumeok.kr', host = 'app.mumeok.kr', site: string | null = 'same-origin') { return new Request(`${origin}/api/v1/marketing/round2`, { method: 'POST', headers: { origin, host, ...(site === null ? {} : { 'sec-fetch-site': site }) } }); }
async function evidence(value: unknown) { const dir = await realpath(await mkdtemp(join(tmpdir(), 'r2-runtime-'))); dirs.push(dir); await chmod(dir, 0o700); const path = join(dir, 'evidence.json'); if (value && typeof value === 'object' && 'proofs' in value) {
  for (const group of ['proofs', 'proxy']) {
    const entries = (value as Record<string, Record<string, unknown>>)[group];
    for (const [key, item] of Object.entries(entries)) {
      if (typeof item === 'string' && /^[b]{64}$/.test(item)) {
        const proof = join(dir, `${group}-${key}.txt`);
        const bytes = JSON.stringify({ release_sha: release, kind: key });
        await writeFile(proof, bytes, { mode: 0o600 });
        entries[key] = { path: proof, sha256: createHash('sha256').update(bytes).digest('hex') };
      }
    }
  }
} await writeFile(path, JSON.stringify(value), { mode: 0o600 }); return path; }
function productionEvidence(vars: Record<string, string>) { return { version: 1, profile: 'production', release_sha: release, origin: 'https://app.mumeok.kr', hostname: 'app.mumeok.kr', verified_at: '2026-09-11T00:00:00Z', consent_generation: 1, secret_fingerprints: Object.fromEntries([...names.map(name => [name.toLowerCase(), createHash('sha256').update(vars[`MUMEOK_ROUND2_${name}_SECRET`]).digest('hex')]), ['turnstile', createHash('sha256').update(vars.MUMEOK_ROUND2_TURNSTILE_SECRET_KEY).digest('hex')]]), proofs: Object.fromEntries(['turnstile_live', 'db_migration', 'db_authority', 'privacy_consent', 'retention_runbook', 'operator_approval'].map(key => [key, 'b'.repeat(64)])), proxy: { header: 'cf-connecting-ip', binding: 'loopback-only', ingress: 'cloudflare-tunnel', direct_access_denial: 'b'.repeat(64), header_overwrite: 'b'.repeat(64), launch_binding: 'b'.repeat(64) } }; }
afterEach(async () => { await Promise.all(dirs.splice(0).map(dir => rm(dir, { recursive: true, force: true }))); });
describe('round2 runtime boundary', () => {
  it('defaults disabled regardless of v2 flags', () => { const config = readRound2RuntimeConfig({ MARKETING_VALIDATION_ENABLED: 'true' }); expect(config.enabled).toBe(false); expect(config.leadsEnabled).toBe(false); expect(() => assertRound2Collection(config, control, now)).toThrow(); });
  it('requires both collection flags and exact campaign time window', () => { const config = readRound2RuntimeConfig(env()); expect(() => assertRound2Collection(config, control, now)).not.toThrow(); for (const time of [Date.parse('2026-09-10T14:59:59Z'), Date.parse('2026-10-31T15:00:00Z')])
    expect(() => assertRound2Collection(config, control, time)).toThrow(); expect(() => assertRound2Collection(config, { ...control, collection_enabled: false }, now)).toThrow(); });
  it('rejects missing weak repeated shared and v2-reused keys without exposing values', () => { for (const change of [{ MUMEOK_ROUND2_PAGE_SECRET: '' }, { MUMEOK_ROUND2_PAGE_SECRET: 'x'.repeat(64) }, { MUMEOK_ROUND2_PAGE_SECRET: 'short' }])
    expect(() => assertRound2Secrets(readRound2RuntimeConfig({ ...env(), ...change }))).toThrow(); const vars = env(); vars.MUMEOK_ROUND2_COOKIE_SECRET = vars.MUMEOK_ROUND2_PAGE_SECRET; expect(() => assertRound2Secrets(readRound2RuntimeConfig(vars))).toThrow(); const reused = env(); reused.MARKETING_TURNSTILE_SECRET = reused.MUMEOK_ROUND2_EVENT_SECRET; expect(() => assertRound2Secrets(readRound2RuntimeConfig(reused))).toThrow(); expect(() => assertRound2Secrets(readRound2RuntimeConfig(env()))).not.toThrow(); });
  it('accepts exact origin and absent fetch-site while rejecting port scheme host null and cross-site', () => { const config = readRound2RuntimeConfig(env()); expect(() => assertRound2Origin(request(), config)).not.toThrow(); expect(() => assertRound2Origin(request(undefined, undefined, null), config)).not.toThrow(); for (const req of [request('http://app.mumeok.kr'), request('https://app.mumeok.kr:443'), request('https://app.mumeok.kr', 'app.mumeok.kr:443'), request(undefined, undefined, 'same-site')])
    expect(() => assertRound2Origin(req, config)).toThrow(); const missing = request(); missing.headers.delete('origin'); expect(() => assertRound2Origin(missing, config)).toThrow(); });
  it('limits preview to exact loopback hosts and always closes POST even if enabled', () => { const config = readRound2RuntimeConfig({ ...env(), MUMEOK_ROUND2_LOCAL_PREVIEW: 'true' }); for (const host of ['localhost:3000', '127.0.0.1:3000', '[::1]:3000'])
    expect(isRound2LocalPreview(host, config)).toBe(true); for (const host of ['app.mumeok.kr', 'localhost.evil:3000', '127.1:3000'])
    expect(isRound2LocalPreview(host, config)).toBe(false); expect(() => assertRound2Collection(config, control, now)).toThrow(); });
  it('rejects boolean-only lead readiness and mismatched release evidence', async () => { const vars = env(); await expect(checkRound2LeadReadiness(readRound2RuntimeConfig(vars), control, now)).rejects.toThrow(); vars.MUMEOK_ROUND2_READINESS_PATH = await evidence({ ...productionEvidence(vars), release_sha: 'c'.repeat(40) }); await expect(checkRound2LeadReadiness(readRound2RuntimeConfig(vars), control, now)).rejects.toThrow(); vars.MUMEOK_ROUND2_READINESS_PATH = await evidence(productionEvidence(vars)); await expect(checkRound2LeadReadiness(readRound2RuntimeConfig(vars), control, now)).resolves.toBeUndefined(); await expect(checkRound2LeadReadiness(readRound2RuntimeConfig(vars), { ...control, lead_enabled: false }, now)).rejects.toThrow(); });
  it('rejects incomplete or world-readable approval evidence', async () => { const vars = env(); vars.MUMEOK_ROUND2_READINESS_PATH = await evidence({ ...productionEvidence(vars), proofs: { operator_approval: true } }); await expect(checkRound2LeadReadiness(readRound2RuntimeConfig(vars), control, now)).rejects.toThrow(); vars.MUMEOK_ROUND2_READINESS_PATH = await evidence(productionEvidence(vars)); await chmod(vars.MUMEOK_ROUND2_READINESS_PATH, 0o644); await expect(checkRound2LeadReadiness(readRound2RuntimeConfig(vars), control, now)).rejects.toThrow(); });
  it('trusts only the single CF header with verified ingress evidence', async () => { const vars = env(); vars.MUMEOK_ROUND2_READINESS_PATH = await evidence(productionEvidence(vars)); const config = readRound2RuntimeConfig(vars); const req = request(); req.headers.set('cf-connecting-ip', '203.0.113.5'); req.headers.set('x-forwarded-for', '198.51.100.4'); await expect(resolveRound2TrustedIp(req, readRound2RuntimeConfig(env()))).rejects.toThrow(); await expect(resolveRound2TrustedIp(req, config)).resolves.toBe('203.0.113.5'); req.headers.set('cf-connecting-ip', '203.0.113.5, 203.0.113.6'); await expect(resolveRound2TrustedIp(req, config)).rejects.toThrow(); });
  it('keeps an old approval closed after the consent generation changes', async () => {
    const vars = env();
    vars.MUMEOK_ROUND2_READINESS_PATH = await evidence(productionEvidence(vars));
    await expect(checkRound2LeadReadiness(readRound2RuntimeConfig(vars), { ...control, consent_generation: 2 }, now)).rejects.toThrow('알림 신청 준비 중이에요.');
    vars.MUMEOK_ROUND2_READINESS_PATH = await evidence({ ...productionEvidence(vars), consent_generation: 2 });
    await expect(checkRound2LeadReadiness(readRound2RuntimeConfig(vars), { ...control, consent_generation: 2 }, now)).resolves.toBeUndefined();
  });
  it('allows anonymous collection with ingress proof before lead proofs exist', async () => { const vars = env(); vars.MUMEOK_ROUND2_LEADS_ENABLED = 'false'; vars.MUMEOK_ROUND2_READINESS_PATH = await evidence({ ...productionEvidence(vars), proofs: {} }); const config = readRound2RuntimeConfig(vars); const req = request(); req.headers.set('cf-connecting-ip', '203.0.113.7'); await expect(resolveRound2TrustedIp(req, config)).resolves.toBe('203.0.113.7'); await expect(checkRound2LeadReadiness(config, control, now)).rejects.toThrow(); });
  it('rejects modified proof files and keys outside the approved release evidence', async () => { const vars = env(); const proof = productionEvidence(vars); vars.MUMEOK_ROUND2_READINESS_PATH = await evidence(proof); const config = readRound2RuntimeConfig(vars); await expect(checkRound2LeadReadiness(config, control, now)).resolves.toBeUndefined(); await expect(checkRound2LeadReadiness(readRound2RuntimeConfig({ ...vars, MUMEOK_ROUND2_EVENT_SECRET: randomBytes(32).toString('base64url') }), control, now)).rejects.toThrow(); const ref = proof.proofs.operator_approval as unknown as {
    path: string;
  }; await writeFile(ref.path, 'modified'); await expect(checkRound2LeadReadiness(config, control, now)).rejects.toThrow(); });
  it('requires explicit isolated identity binding DB rate control and test keys without production mixing', async () => { const vars = { ...env(), NODE_ENV: 'test', MUMEOK_ROUND2_PROFILE: 'isolated', MUMEOK_ROUND2_RATE_STATE_DIR: '/tmp/r2-test/rate', MUMEOK_ROUND2_CONTROL_PATH: '/tmp/r2-test/control.json', DATA_SUPABASE_URL: 'http://127.0.0.1:54399' }; const config = readRound2RuntimeConfig(vars); expect(config.origin).toBe('https://localhost:3443'); await expect(resolveRound2TrustedIp(request('https://localhost:3443', 'localhost:3443'), config)).rejects.toThrow(); const identity = { version: 1, profile: 'isolated', namespace: 'r2-test', origin: 'https://localhost:3443', hostname: 'localhost', db_origin: vars.DATA_SUPABASE_URL, rate_state_dir: vars.MUMEOK_ROUND2_RATE_STATE_DIR, control_path: vars.MUMEOK_ROUND2_CONTROL_PATH, secret_fingerprints: Object.fromEntries(names.map(name => [name.toLowerCase(), createHash('sha256').update(vars[`MUMEOK_ROUND2_${name}_SECRET` as keyof typeof vars]).digest('hex')])) }; const path = await evidence(identity); const valid = readRound2RuntimeConfig({ ...vars, MUMEOK_ROUND2_ISOLATED_IDENTITY_PATH: path }); await expect(resolveRound2TrustedIp(request('https://localhost:3443', 'localhost:3443'), valid)).resolves.toBe('127.0.0.1'); await expect(resolveRound2TrustedIp(request(), valid)).rejects.toThrow(); await expect(resolveRound2TrustedIp(request('https://localhost:3443', 'localhost:3443'), readRound2RuntimeConfig({ ...vars, NODE_ENV: 'production', MUMEOK_ROUND2_ISOLATED_IDENTITY_PATH: path }))).rejects.toThrow(); });
});
