// Explicit infra-only files: additions require checking imports and indirect file reads.
// Unknown tests remain in product. Authority evidence and local runtime stay in product.
export const HARNESS_TEST_FILES = [
  "tests/agent-plan-loop.test.ts",
  "tests/agent-review-loop.test.ts",
  "tests/bookkeeping-authority.test.ts",
  "tests/check-workpack-docs.test.ts",
  "tests/ci-path-filter.test.ts",
  "tests/closeout-sync-validator.test.ts",
  "tests/edit-branch-guard.test.ts",
  "tests/exploratory-qa-evidence.test.ts",
  "tests/frontend-design-skill.test.ts",
  "tests/git-policy.test.ts",
  "tests/meta-harness-auditor.test.ts",
  "tests/next-routes-manifest.test.ts",
  "tests/omo-automation-spec.test.ts",
  "tests/omo-autonomous-supervisor.test.ts",
  "tests/omo-bookkeeping.test.ts",
  "tests/omo-checklist-contract.test.ts",
  "tests/omo-closeout-state.test.ts",
  "tests/omo-control-plane-smoke.test.ts",
  "tests/omo-doc-gate.test.ts",
  "tests/omo-evaluator.test.ts",
  "tests/omo-github.test.ts",
  "tests/omo-lite-budget.test.ts",
  "tests/omo-lite-config.test.ts",
  "tests/omo-lite-runner.test.ts",
  "tests/omo-lite-supervisor.test.ts",
  "tests/omo-promotion-evidence.test.ts",
  "tests/omo-provider-guard.test.ts",
  "tests/omo-provider-smoke.test.ts",
  "tests/omo-replay-acceptance.test.ts",
  "tests/omo-scheduler.test.ts",
  "tests/omo-session-orchestrator.test.ts",
  "tests/omo-session-runtime.test.ts",
  "tests/omo-slice-report.test.ts",
  "tests/omo-stage-result.test.ts",
  "tests/omo-status-summary.test.ts",
  "tests/omo-tail.test.ts",
  "tests/omo-tracked-work-item-recovery.test.ts",
  "tests/omo-worktree-manager.test.ts",
  "tests/playwright-workflow.test.ts",
  "tests/policy-workflow.test.ts",
  "tests/production-data-quality.test.ts",
  "tests/production-release-rulesets-c2.test.ts",
  "tests/production-release-rulesets.test.ts",
  "tests/project-hooks-config.test.ts",
  "tests/qa-system.test.ts",
  "tests/real-smoke-presence.test.ts",
  "tests/source-of-truth-sync.test.ts",
  "tests/start-work-branch.test.ts",
  "tests/workflow-concurrency.test.ts",
  "tests/workflow-v2-closeout-projection.test.ts",
  "tests/workflow-v2-docs.test.ts",
];

export const ALL_TEST_PATTERNS = ["tests/**/*.test.ts", "tests/**/*.test.tsx"];
